name: test

on:
  push:
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nim-version: ["2.0.14", "stable"]
    steps:
      - uses: actions/checkout@v4
      - uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: ${{ matrix.nim-version }}
      - name: Test ORC and ARC builds
        run: nimble test -y
      - name: Compile precision example
        run: nim c -r --path:src examples/precision.nim
